tasks:
  - init: echo ""
    command: (openbox &) && (klayout -e &) && (xclock -update 1 -geometry 16x16-0+0 &) && (wget https://raw.githubusercontent.com/yuanliuus/MaskFiles/master/.gitpod.yml -q -O .gitpod.yml)
image: lewisyuan/masklayout

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
    
vscode:
  extensions:
    - ms-vscode.cmake-tools
    - llvm-vs-code-extensions.vscode-clangd
